- name: Check versions
  hosts: swift
  gather_facts: no
  tasks:
    - command: "lsb_release -ds"
      register: linux_version
    - name: "Linux version"
      debug:
        msg: "{{ linux_version.stdout }}"

    - command: "python3 --version"
      register: python_version
    - name: "Python version"
      debug:
        msg: "{{ python_version.stdout }}"

    - shell: "pip freeze | sort | md5sum"
      register: pip_versions_hash
    - name: "Hash of Python packages"
      debug:
        msg: "{{ pip_versions_hash.stdout }}"

    - command: "pip freeze"
      register: pip_versions
    - name: "Python packages"
      debug:
        var: pip_versions.stdout_lines
